/* Betel Radar v0.8.1 — produtividade, build 8102 */
(function(){
 const VERSION='v0.8.1';
 const ops=()=>Array.isArray(window.opportunities)?window.opportunities:[];
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const csv=v=>'"'+String(v??'').replace(/"/g,'""')+'"';
 function dl(name,rows){const b=new Blob(['\ufeff'+rows.map(r=>r.map(csv).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
 function visibleHeading(txt){return [...document.querySelectorAll('h1,h2,h3')].find(e=>e.offsetParent!==null&&e.textContent.trim().toLowerCase().includes(txt));}
 function viewRoot(h){return h?.closest('.view,.content-view,.page,.panel')||h?.parentElement?.parentElement||document.body;}
 function date(v){const d=new Date(v);return isNaN(d)?null:d} function day(d){const x=new Date(d);x.setHours(0,0,0,0);return x}
 function agenda(){const h=visibleHeading('agenda comercial');if(!h)return;const root=viewRoot(h);let box=root.querySelector('#agendaProductivity');if(box)box.remove();const list=ops().filter(o=>o.followUp&&date(o.followUp));const t=day(new Date()),tm=new Date(t);tm.setDate(tm.getDate()+1);const e7=new Date(t);e7.setDate(e7.getDate()+8);const nToday=list.filter(o=>{const d=date(o.followUp);return d>=t&&d<tm}).length,n7=list.filter(o=>{const d=date(o.followUp);return d>=tm&&d<e7}).length,late=list.filter(o=>date(o.followUp)<t).length;box=document.createElement('section');box.id='agendaProductivity';box.className='v081-agenda-box';box.innerHTML=`<div class="v081-kpis"><div><span>Hoje</span><b>${nToday}</b></div><div><span>Próximos 7 dias</span><b>${n7}</b></div><div><span>Atrasados</span><b>${late}</b></div></div><button class="v081-export" id="exportAgendaCsv">⇩ Exportar agenda CSV</button>`;const desc=h.nextElementSibling; (desc||h).insertAdjacentElement('afterend',box);box.querySelector('button').onclick=()=>{const r=[['Oportunidade','Cidade','Anunciante','Status','Follow-up']];list.sort((a,b)=>date(a.followUp)-date(b.followUp)).forEach(o=>r.push([o.title,o.city,o.advertiser,o.status,date(o.followUp).toLocaleString('pt-BR')]));dl('betel-radar-agenda.csv',r)};}
 function finance(){const h=visibleHeading('financeiro comercial');if(!h)return;const root=viewRoot(h);let box=root.querySelector('#financeProductivity');if(box)box.remove();box=document.createElement('section');box.id='financeProductivity';box.className='v081-fin-box';box.innerHTML=`<input id="financeSearch" type="search" placeholder="Buscar oportunidade ou anunciante"><button class="v081-export" id="exportFinanceCsv">⇩ Exportar financeiro CSV</button>`;const desc=h.nextElementSibling;(desc||h).insertAdjacentElement('afterend',box);const input=box.querySelector('input');input.oninput=()=>{const q=input.value.trim().toLowerCase();[...root.querySelectorAll('tbody tr,.finance-card,.financial-card,.proposal-card')].forEach(el=>el.style.display=!q||el.innerText.toLowerCase().includes(q)?'':'none')};box.querySelector('button').onclick=()=>{const r=[['Oportunidade','Anunciante','Proposta','Orçado','Contratado','Recebido','Status']];ops().forEach(o=>r.push([o.title,o.advertiser,o.proposalStatus||o.proposal?.status||'',o.budget||o.proposalValue||o.value||'',o.contractedValue||'',o.receivedValue||'',o.status]));dl('betel-radar-financeiro.csv',r)};}
 function messages(){const h=visibleHeading('gerador de abordagem personalizada');if(!h)return;const root=viewRoot(h);const target=[...root.querySelectorAll('textarea,[contenteditable="true"],div')].find(e=>e.offsetParent!==null&&(/a mensagem aparecerá aqui/i.test(e.getAttribute?.('placeholder')||'')||/a mensagem aparecerá aqui/i.test(e.textContent||'')));if(!target)return;let c=root.querySelector('#v081CharCount');if(!c){c=document.createElement('div');c.id='v081CharCount';c.className='v081-charcount';target.insertAdjacentElement('afterend',c)}const refresh=()=>{const val=('value'in target?target.value:target.textContent)||'';c.textContent=`${val.length} caracteres`};target.addEventListener?.('input',refresh);refresh();setTimeout(refresh,150);}
 function version(){const chip=document.getElementById('versionChip');if(chip)chip.textContent='Betel Radar '+VERSION;}
 function run(){agenda();finance();messages();version()}
 document.addEventListener('click',()=>{setTimeout(run,100);setTimeout(run,400)});const mo=new MutationObserver(()=>{clearTimeout(window.__v081t);window.__v081t=setTimeout(run,80)});mo.observe(document.documentElement,{subtree:true,childList:true});setTimeout(run,500);setInterval(run,2500);
})();