/* Betel Radar v0.8.1 — produtividade, build 8103 */
(function(){
 const VERSION='v0.8.1';
 const ops=()=>Array.isArray(window.opportunities)?window.opportunities:[];
 const csv=v=>'"'+String(v??'').replace(/"/g,'""')+'"';
 function dl(name,rows){const b=new Blob(['\ufeff'+rows.map(r=>r.map(csv).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
 function installStyles(){if(document.getElementById('v081IntegratedStyles'))return;const s=document.createElement('style');s.id='v081IntegratedStyles';s.textContent=`
 .v081-agenda-box,.v081-fin-box{margin:18px 0 20px;border:1px solid #e7e4df;border-radius:20px;background:linear-gradient(180deg,#fff 0%,#faf9f6 100%);box-shadow:0 10px 28px rgba(20,20,20,.055);overflow:hidden}
 .v081-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:15px 17px;border-bottom:1px solid #ece9e4;background:linear-gradient(90deg,#fbfaf7,#fff)}
 .v081-eyebrow{font-size:11px;letter-spacing:.12em;text-transform:uppercase;font-weight:800;color:#a56e35}.v081-title{font-size:15px;font-weight:800;color:#171717;margin-top:2px}.v081-sub{font-size:12px;color:#777;margin-top:2px}
 .v081-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:16px}
 .v081-kpi{position:relative;min-height:92px;padding:15px;border:1px solid #ebe8e2;border-radius:16px;background:#fff;display:flex;flex-direction:column;justify-content:center}.v081-kpi:before{content:'';position:absolute;left:0;top:16px;bottom:16px;width:4px;border-radius:0 4px 4px 0;background:#c08a4d}.v081-kpi.green:before{background:#1ea672}.v081-kpi.red:before{background:#cf4c5d}.v081-kpi span{font-size:12px;color:#6f6f6f;margin-bottom:6px}.v081-kpi b{font-size:28px;line-height:1;color:#171717}.v081-kpi small{font-size:11px;color:#999;margin-top:5px}
 .v081-actions{display:flex;align-items:center;gap:10px;padding:0 16px 16px}.v081-export{appearance:none;border:1px solid #1b1b1b;border-radius:13px;background:#171717;color:#fff;padding:11px 15px;font:inherit;font-weight:800;cursor:pointer;box-shadow:0 6px 14px rgba(0,0,0,.08)}.v081-export:hover{background:#2a2a2a}.v081-secondary{background:#fff;color:#171717;border-color:#dedad4;box-shadow:none}.v081-secondary:hover{background:#f7f5f2}
 .v081-fin-main{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:16px}.v081-search-wrap{position:relative}.v081-search-wrap:before{content:'⌕';position:absolute;left:14px;top:50%;transform:translateY(-52%);font-size:20px;color:#777;pointer-events:none}.v081-fin-box input{width:100%;box-sizing:border-box;border:1px solid #ddd9d3;border-radius:14px;padding:12px 14px 12px 42px;font:inherit;background:#fff;outline:none;transition:.2s}.v081-fin-box input:focus{border-color:#b58a5d;box-shadow:0 0 0 3px rgba(181,138,93,.12)}
 .v081-charcount{display:flex!important;justify-content:flex-end!important;margin:7px 2px 0!important;color:#777!important;font-size:12px!important;min-height:18px!important}.v081-row-link{cursor:pointer}.v081-row-link:hover{background:#faf9f6}
 @media(max-width:760px){.v081-agenda-box,.v081-fin-box{margin:14px 0 18px;border-radius:18px}.v081-head{padding:13px 14px}.v081-kpis{grid-template-columns:1fr;gap:9px;padding:12px}.v081-kpi{min-height:72px;padding:12px 14px}.v081-kpi b{font-size:25px}.v081-actions{padding:0 12px 12px;display:block}.v081-export{width:100%}.v081-fin-main{grid-template-columns:1fr;padding:12px}.v081-fin-main .v081-export{width:100%}.v081-title{font-size:14px}.v081-sub{font-size:11px}}
 `;document.head.appendChild(s)}
 function visibleHeading(txt){return [...document.querySelectorAll('h1,h2,h3')].find(e=>e.offsetParent!==null&&e.textContent.trim().toLowerCase().includes(txt));}
 function viewRoot(h){return h?.closest('.view,.content-view,.page,.panel')||h?.parentElement?.parentElement||document.body;}
 function date(v){const d=new Date(v);return isNaN(d)?null:d} function day(d){const x=new Date(d);x.setHours(0,0,0,0);return x}
 function agenda(){const h=visibleHeading('agenda comercial');if(!h)return;const root=viewRoot(h);let box=root.querySelector('#agendaProductivity');if(box)box.remove();const list=ops().filter(o=>o.followUp&&date(o.followUp));const t=day(new Date()),tm=new Date(t);tm.setDate(tm.getDate()+1);const e7=new Date(t);e7.setDate(e7.getDate()+8);const nToday=list.filter(o=>{const d=date(o.followUp);return d>=t&&d<tm}).length,n7=list.filter(o=>{const d=date(o.followUp);return d>=tm&&d<e7}).length,late=list.filter(o=>date(o.followUp)<t).length;box=document.createElement('section');box.id='agendaProductivity';box.className='v081-agenda-box';box.innerHTML=`<div class="v081-head"><div><div class="v081-eyebrow">Visão de acompanhamento</div><div class="v081-title">Resumo dos follow-ups</div><div class="v081-sub">Priorize retornos e compromissos comerciais.</div></div></div><div class="v081-kpis"><div class="v081-kpi"><span>Hoje</span><b>${nToday}</b><small>retornos previstos</small></div><div class="v081-kpi green"><span>Próximos 7 dias</span><b>${n7}</b><small>acompanhamentos programados</small></div><div class="v081-kpi red"><span>Atrasados</span><b>${late}</b><small>precisam de atenção</small></div></div><div class="v081-actions"><button class="v081-export" id="exportAgendaCsv">⇩ Exportar agenda em CSV</button></div>`;const desc=h.nextElementSibling;(desc||h).insertAdjacentElement('afterend',box);box.querySelector('button').onclick=()=>{const r=[['Oportunidade','Cidade','Anunciante','Status','Follow-up']];list.sort((a,b)=>date(a.followUp)-date(b.followUp)).forEach(o=>r.push([o.title,o.city,o.advertiser,o.status,date(o.followUp).toLocaleString('pt-BR')]));dl('betel-radar-agenda.csv',r)};}
 function finance(){const h=visibleHeading('financeiro comercial');if(!h)return;const root=viewRoot(h);let box=root.querySelector('#financeProductivity');if(box)box.remove();box=document.createElement('section');box.id='financeProductivity';box.className='v081-fin-box';box.innerHTML=`<div class="v081-head"><div><div class="v081-eyebrow">Ferramentas financeiras</div><div class="v081-title">Consulta e exportação</div><div class="v081-sub">Localize rapidamente propostas e gere uma planilha do módulo.</div></div></div><div class="v081-fin-main"><div class="v081-search-wrap"><input id="financeSearch" type="search" placeholder="Buscar oportunidade ou anunciante"></div><button class="v081-export" id="exportFinanceCsv">⇩ Exportar financeiro em CSV</button></div>`;const desc=h.nextElementSibling;(desc||h).insertAdjacentElement('afterend',box);const input=box.querySelector('input');input.oninput=()=>{const q=input.value.trim().toLowerCase();[...root.querySelectorAll('tbody tr,.finance-card,.financial-card,.proposal-card')].forEach(el=>el.style.display=!q||el.innerText.toLowerCase().includes(q)?'':'none')};box.querySelector('button').onclick=()=>{const r=[['Oportunidade','Anunciante','Proposta','Orçado','Contratado','Recebido','Status']];ops().forEach(o=>r.push([o.title,o.advertiser,o.proposalStatus||o.proposal?.status||'',o.budget||o.proposalValue||o.value||'',o.contractedValue||'',o.receivedValue||'',o.status]));dl('betel-radar-financeiro.csv',r)};}
 function messages(){const h=visibleHeading('gerador de abordagem personalizada');if(!h)return;const root=viewRoot(h);const target=[...root.querySelectorAll('textarea,[contenteditable="true"],div')].find(e=>e.offsetParent!==null&&(/a mensagem aparecerá aqui/i.test(e.getAttribute?.('placeholder')||'')||/a mensagem aparecerá aqui/i.test(e.textContent||'')));if(!target)return;let c=root.querySelector('#v081CharCount');if(!c){c=document.createElement('div');c.id='v081CharCount';c.className='v081-charcount';target.insertAdjacentElement('afterend',c)}const refresh=()=>{const val=('value'in target?target.value:target.textContent)||'';c.textContent=`${val.length} caracteres`};target.addEventListener?.('input',refresh);refresh();setTimeout(refresh,150);}
 function version(){const chip=document.getElementById('versionChip');if(chip)chip.textContent='Betel Radar '+VERSION;}
 function run(){installStyles();agenda();finance();messages();version()}
 document.addEventListener('click',()=>{setTimeout(run,100);setTimeout(run,400)});const mo=new MutationObserver(()=>{clearTimeout(window.__v081t);window.__v081t=setTimeout(run,100)});mo.observe(document.documentElement,{subtree:true,childList:true});setTimeout(run,500);setInterval(run,3000);
})();